export const GET_AUDIO_STREAM = "REQUEST_AUDIO_PERMISSION";
export const GET_AUDIO_STREAM_FAIL = "REQUEST_AUDIO_PERMISSION_FAIL";

export const SET_PEER_CONNECTION = "SET_PEER_CONNECTION";

export const SET_CALL_ACCEPTED = "SET_CALL_ACCEPTED";

export const SET_CALL_ENDED = "SET_CALL_ENDED";
export const RESET_CALL = "RESET_CALL";

export const SET_USER_AUDIO = "SET_USER_AUDIO";
