export const SOCKET_CONNECT = "SOCKET_CONNECT";

export const GET_ONLINE_USERS = "GET_ONLINE_USERS";

export const LISTEN_INCOMING_CALL = "LISTEN_INCOMING_CALL";

export const LISTEN_MY_SOCKET_ID = "LISTEN_MY_SOCKET_ID";

export const RESET_INCOMING_CALL = "RESET_INCOMING_CALL";
