export const SOCKET_CONNECT = "SOCKET_CONNECT";

export const EMIT_USER_JOINED = "EMIT_USER_JOINED";
export const EMIT_NEW_ICE_CANDIDATE = "EMIT_NEW_ICE_CANDIDATE";
export const EMIT_ANSWER_CALL = "EMIT_ANSWER_CALL";
export const EMIT_CALL_USER = "EMIT_CALL_USER";

export const LISTEN_ME = "LISTEN_ME";
export const LISTEN_NEW_USER = "LISTEN_NEW_USER";
export const LISTEN_CALL_USER = "LISTEN_CALL_USER";
export const LISTEN_CALL_ACCEPTED = "LISTEN_CALL_ACCEPTED";
export const LISTEN_NEW_ICE_CANDIDATE = "LISTEN_NEW_ICE_CANDIDATE";
